### ISSUE TITLE
Syntax error with with node.js v0.10.26

### ISSUE THREAD

**Issue by sneilan** [w3c/Mobile-Checker#134]
git clone https://github.com/w3c/Mobile-Checker.git
cd Mobile-Checker
npm install -d
node app.js

/Users/sneilan/Downloads/Mobile-Checker/node_modules/mobile-web-browser-emulator/node_modules/selenium-webdriver/index.js:25
const builder = require('./builder');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/sneilan/Downloads/Mobile-Checker/node_modules/mobile-web-browser-emulator/lib/browser-emulator.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by sneilan** [comment]
Nevermind, using the latest version of node.js 5.7.0 worked!
