### ISSUE TITLE
websites & app which generate bugs or invalid issues

### ISSUE THREAD

**Issue by guibbs** [w3c/Mobile-Checker#50]
- http://www.canalplus.fr/c-cinema/c-les-films-en-salles/cid354533-carlos-le-film.html (prefixed css test)

**Comment by guibbs** [comment]
seems to work now except for the screenshot.

**Comment by guibbs** [comment]
generate error:

/Users/guillaume/Documents/w3c/mobile_checker/node_modules/css/lib/parse/index.js:129
    css = css.slice(str.length);
              ^
TypeError: Cannot call method 'slice' of undefined
    at match (/Users/guillaume/Documents/w3c/mobile_checker/node_modules/css/lib/parse/index.js:129:15)
    at whitespace (/Users/guillaume/Documents/w3c/mobile_checker/node_modules/css/lib/parse/index.js:138:5)
    at rules (/Users/guillaume/Documents/w3c/mobile_checker/node_modules/css/lib/parse/index.js:109:5)
    at stylesheet (/Users/guillaume/Documents/w3c/mobile_checker/node_modules/css/lib/parse/index.js:81:16)
    at Object.module.exports [as parse] (/Users/guillaume/Documents/w3c/mobile_checker/node_modules/css/lib/parse/index.js:558:20)
    at null.<anonymous> (/Users/guillaume/Documents/w3c/mobile_checker/lib/checks/compatibility/css-prefixes.js:29:48)
    at emit (events.js:117:20)
    at reportNetworkTraffic (/Users/guillaume/Documents/w3c/mobile_checker/node_modules/mobile-web-browser-emulator/lib/browser-emulator.js:107:14)
    at /Users/guillaume/Documents/w3c/mobile_checker/node_modules/mobile-web-browser-emulator/node_modules/browsermob-proxy/index.js:55:41
    at IncomingMessage.<anonymous> (/Users/guillaume/Documents/w3c/mobile_checker/node_modules/mobile-web-browser-emulator/node_modules/browsermob-proxy/index.js:211:17)
